<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <meta name="description" content="">
    <meta name="author" content="">

    <!-- Bootstrap core CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-gH2yIJqKdNHPEq0n4Mqa/HGKIhSkIHeL5AyhkYV8i59U5AR6csBvApHHNl/vI1Bx" crossorigin="anonymous">

    <link href="css/my-style.css" rel="stylesheet">

    <title>ParcelPal</title>
</head>

<body role="document">

<div class="navbar">
    <a class="navbar-brand" href="#">ParcelPal</a>
    <?php if (isset($userData)): ?>
        <!-- User is logged in -->
        <form method="get">
            <label>
                <input type="text" name="search" placeholder="Search here...">
            </label>
            <button class="green-button" type="submit">Search</button>
        </form>
        <form action="logoutController.php" method="post">
            <button class="red-button" type="submit" name="logout">Logout</button>
        </form>
    <?php endif; ?>
</div>